version: '3.8'

services:
  browser-use-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browser-use-api
    ports:
      - "8000:8000"
    environment:
      - USE_PROXY=${USE_PROXY:-false}
      - PROXY_SERVER=${PROXY_SERVER:-}
      - PROXY_USERNAME=${PROXY_USERNAME:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - SKIP_LLM_API_KEY_VERIFICATION=${SKIP_LLM_API_KEY_VERIFICATION:-true}
      - CLOUD_BROWSER_URL=${CLOUD_BROWSER_URL:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET=${S3_BUCKET:-}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    shm_size: 2gb  # Increase shared memory for browser stability

  # Optional Redis service for state persistence
  redis:
    image: redis:7-alpine
    container_name: browser-use-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
